<a href="https://colab.research.google.com/github/diegosfc91/Proyecto-I.-An-lisis-y-predicci-n-de-ventas-Part-1-Core-/blob/main/An%C3%A1lisis_de_Datos_con_NumPy_(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Definición de funciones

def generar_datos_ventas(productos, tiendas, dias):
   # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    return np.random.randint(0, 101, (productos, tiendas, dias))

def calcular_totales_ventas_por_producto(datos):
    """Calcula el total de ventas por producto a lo largo de la semana."""
    return np.sum(datos, axis=(1, 2))

def calcular_totales_ventas_por_tienda(datos):
    """Calcula el total de ventas por tienda a lo largo de la semana."""
    return np.sum(datos, axis=(0, 2))

def calcular_promedio_ventas_por_producto(datos):
    """Calcula el promedio de ventas por producto por día."""
    return np.mean(datos, axis=(1, 2))

def calcular_promedio_ventas_por_tienda(datos):
    """Calcula el promedio de ventas por tienda por día."""
    return np.mean(datos, axis=(0, 2))

def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    """Encuentra el producto con mayor y menor ventas totales en la semana."""
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    """Encuentra la tienda con mayor y menor ventas totales en la semana."""
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

def imprimir_resumen(totales_por_producto, totales_por_tienda, promedio_por_producto, promedio_por_tienda,
                     producto_mayor_ventas, producto_menor_ventas, tienda_mayor_ventas, tienda_menor_ventas):
    """Imprime un resumen de las ventas."""
    print("Resumen de Ventas:")
    print("-" * 50)
    print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
    print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
    print("Promedio de ventas por producto por día:", promedio_por_producto)
    print("Promedio de ventas por tienda por día:", promedio_por_tienda)
    print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
    print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
    print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
    print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")
    print("-" * 50)

# Parámetros
productos = 10
tiendas = 7
dias = 5

# Generación de los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)
print(datos)
# Cálculo de los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

# Imprimir los resultados
imprimir_resumen(totales_por_producto, totales_por_tienda, promedio_por_producto, promedio_por_tienda,
                 producto_mayor_ventas, producto_menor_ventas, tienda_mayor_ventas, tienda_menor_ventas)


[[[15 17 93]
  [26 14 77]]

 [[70 68  6]
  [18  2 40]]

 [[93 58 24]
  [58 25 98]]]
Resumen de Ventas:
--------------------------------------------------
Total de ventas por producto a lo largo de la semana: [242 204 356]
Total de ventas por tienda a lo largo de la semana: [444 358]
Promedio de ventas por producto por día: [40.33333333 34.         59.33333333]
Promedio de ventas por tienda por día: [49.33333333 39.77777778]
Producto con mayor ventas: Producto 2
Producto con menor ventas: Producto 1
Tienda con mayor ventas: Tienda 0
Tienda con menor ventas: Tienda 1
--------------------------------------------------
